entities:list :
  class: Pegase\External\Doctrine2\ORM\Command\Entity
  method: entity_list_command
  parameters: entity_list_command_parameters

entities:create :
  class: Pegase\External\Doctrine2\ORM\Command\Entity
  method: create_command
  parameters: create_command_parameters

database:create :
  class: Pegase\External\Doctrine2\ORM\Command\Database
  method: create_command
  parameters: create_command_parameters

database:drop :
  class: Pegase\External\Doctrine2\ORM\Command\Database
  method: drop_command
  parameters: drop_command_parameters

# Doctrine database schema management commands:
# prefix used: 'schema:'

schema:create :
  class: Pegase\External\Doctrine2\ORM\Command\Schema
  method: create_command
  parameters: create_command_parameters

schema:create_dump_sql :
  class: Pegase\External\Doctrine2\ORM\Command\Schema
  method: create_dump_sql_command
  parameters: create_dump_sql_command_parameters

schema:update :
  class: Pegase\External\Doctrine2\ORM\Command\Schema
  method: update_command
  parameters: update_command_parameters

schema:update_dump_sql :
  class: Pegase\External\Doctrine2\ORM\Command\Schema
  method: update_dump_sql_command
  parameters: update_dump_sql_command_parameters

schema:drop :
  class: Pegase\External\Doctrine2\ORM\Command\Schema
  method: drop_command
  parameters: drop_command_parameters

schema:drop_dump_sql :
  class: Pegase\External\Doctrine2\ORM\Command\Schema
  method: drop_dump_sql_command
  parameters: drop_dump_sql_command_parameters
